

// Write a function `printCombinations`that accepts two arrays as arguments. The function should
// print all combinations of the elements generated by taking an element from the first array and
// and an element from the second array. The function doesn't need to return any value. It
// should just print to the terminal.

let printCombinations = (a1, a2) => {
  for (let i = 0; i < a1.length; i++) {
    for (let j = 0; j < a2.length; j++) {
      console.log(a1[i], a2[j]);
    }
  }
};

let colors = ['gray', 'cream', 'cyan'];
let clothes = ['shirt', 'flannel'];
printCombinations(colors, clothes);
// prints
//  gray shirt
//  gray flannel
//  cream shirt
//  cream flannel
//  cyan shirt
//  cyan flannel

printCombinations(['hot', 'cold'], ['soup', 'tea']);
// prints
//  hot soup
//  hot tea
//  cold soup
//  cold tea

console.log('============================================');
// Write a function `twoSum(numbers, target)` that accepts an array of numbers and a target number
// as an argument. The function should return a boolean indicating whether or not there exists a pair
// of distinct elements in the array that sum to the target.

let twoSum = (numz, target) => {
  for (let i = 0; i < numz.length; i++) {
    for (let j = i + 1; j < numz.length; j++) {
      if (numz[i] + numz[j] === target) {
        return true;
      }
    }
  }
  return false;
};

console.log(twoSum([2, 3, 5, 9], 7)); // true
console.log(twoSum([2, 3, 5, 9], 4)); // false
console.log(twoSum([6, 3, 4], 10)); // true
console.log(twoSum([6, 5, 1], 10)); // false
